#pragma once

#include <stddef.h>
#include <stdint.h>
#include "config.h"
#include "chord_engine.h"

#define CONTROL_PROTOCOL_PREFIX "MS16/1"
#define CONTROL_REQUEST_ID_LEN 16
#define CONTROL_LINE_MAX 128

enum ControlCommand : uint8_t {
    CONTROL_NONE = 0,
    CONTROL_PING,
    CONTROL_STATUS,
    CONTROL_TRANSPORT_START,
    CONTROL_TRANSPORT_CONTINUE,
    CONTROL_TRANSPORT_STOP,
    CONTROL_TEMPO_SET,
    CONTROL_NOTE_ON,
    CONTROL_NOTE_OFF,
    CONTROL_DRUM_HIT,
    CONTROL_SD_TEST,
    CONTROL_MASTER_START,
    CONTROL_MASTER_STOP,
    CONTROL_STEM_START,
    CONTROL_STEM_STOP,
    CONTROL_LOOP_STATUS,
    CONTROL_LOOP_RECORD,
    CONTROL_LOOP_STOP,
    CONTROL_LOOP_MUTE,
    CONTROL_LOOP_UNMUTE,
    CONTROL_LOOP_CLEAR,
    CONTROL_LOOP_VOLUME,
    CONTROL_LOOP_SOLO,
    CONTROL_LOOP_UNSOLO,
    CONTROL_LOOP_PAUSE,
    CONTROL_LOOP_RESUME,
    CONTROL_LOOP_METRONOME_ON,
    CONTROL_LOOP_METRONOME_OFF,
    CONTROL_SAMPLE_STATUS,
    CONTROL_SAMPLE_ASSIGN,
    CONTROL_SAMPLE_TRIGGER,
    CONTROL_SAMPLE_CLEAR,
    CONTROL_SAMPLE_RECORD,
    CONTROL_SAMPLE_STOP,
    CONTROL_EVENT_STATUS,
    CONTROL_EVENT_ARM,
    CONTROL_EVENT_DISARM,
    CONTROL_EVENT_MUTE,
    CONTROL_EVENT_UNMUTE,
    CONTROL_EVENT_CLEAR,
    CONTROL_EVENT_BARS,
    CONTROL_MOTION_STATUS,
    CONTROL_MOTION_MAP,
    CONTROL_MOTION_CLEAR,
    CONTROL_MIDI_STATUS,
    CONTROL_PROJECT_STATUS,
    CONTROL_PROJECT_SAVE,
    CONTROL_PROJECT_LOAD,
    CONTROL_BOOT_STATUS,
    CONTROL_BOOT_NORMAL,
    CONTROL_BOOT_USB_HOST,
    CONTROL_SYNTH_STATUS,
    CONTROL_SYNTH_ENGINE,
    CONTROL_SYNTH_SET,
    CONTROL_SYNTH_DSP_RESET,
    CONTROL_CHORD_STATUS,
    CONTROL_CHORD_PLAY,
    CONTROL_CHORD_OFF,
    CONTROL_CHORD_SET,
    CONTROL_CHORD_LOCK,
    CONTROL_CHORD_UNLOCK,
    CONTROL_CHORD_INVERSION,
    CONTROL_CHORD_OCTAVE_SHIFT,
    CONTROL_PO_EFFECT,
    CONTROL_PO_LOCK,
    CONTROL_MEDO_STATUS,
    CONTROL_MEDO_ROLE,
    CONTROL_MEDO_QUANTIZE,
    CONTROL_MEDO_SET,
    CONTROL_CAP_STATUS,
    CONTROL_CAP_PAIR,
    CONTROL_CAP_DISCONNECT,
    CONTROL_CAP_MONITOR,
    CONTROL_CAP_CLEAR,
};

enum ControlParseStatus : uint8_t {
    CONTROL_PARSE_OK = 0,
    CONTROL_PARSE_EMPTY,
    CONTROL_PARSE_BAD_PREFIX,
    CONTROL_PARSE_MISSING_ID,
    CONTROL_PARSE_BAD_ID,
    CONTROL_PARSE_UNKNOWN_COMMAND,
    CONTROL_PARSE_BAD_ARGUMENTS,
};

struct ControlRequest {
    char id[CONTROL_REQUEST_ID_LEN];
    ControlCommand command;
    uint16_t arg1;
    uint16_t arg2;
    uint16_t arg3;
    char text[SAMPLE_NAME_LEN];
};

ControlParseStatus controlParseLine(const char* line, ControlRequest& request);
const char* controlParseStatusName(ControlParseStatus status);
