#pragma once

#include "synth_engine.h"

#include <stdint.h>

enum SynthParameter : uint8_t {
    SYNTH_PARAM_ENGINE = 0,
    SYNTH_PARAM_VOICES,
    SYNTH_PARAM_VOLUME,
    SYNTH_PARAM_MG_OSC,
    SYNTH_PARAM_MG_WAVETABLE,
    SYNTH_PARAM_MG_CUTOFF,
    SYNTH_PARAM_MG_RESONANCE,
    SYNTH_PARAM_MG_FILTER_ENV,
    SYNTH_PARAM_MG_FILTER_DECAY,
    SYNTH_PARAM_MG_AMP_DECAY,
    SYNTH_PARAM_MGX_OSC,
    SYNTH_PARAM_MGX_WAVETABLE,
    SYNTH_PARAM_MGX_FILTER_MODE,
    SYNTH_PARAM_MGX_CUTOFF,
    SYNTH_PARAM_MGX_RESONANCE,
    SYNTH_PARAM_MGX_FILTER_ENV,
    SYNTH_PARAM_MGX_PULSE_WIDTH,
    SYNTH_PARAM_MGX_SUB_LEVEL,
    SYNTH_PARAM_MGX_DRIVE,
    SYNTH_PARAM_MGX_VELOCITY_AMP,
    SYNTH_PARAM_MGX_VELOCITY_FILTER,
    SYNTH_PARAM_MGX_AMP_ATTACK,
    SYNTH_PARAM_MGX_AMP_DECAY,
    SYNTH_PARAM_MGX_AMP_SUSTAIN,
    SYNTH_PARAM_MGX_AMP_RELEASE,
    SYNTH_PARAM_MGX_FILTER_ATTACK,
    SYNTH_PARAM_MGX_FILTER_DECAY,
    SYNTH_PARAM_MGX_FILTER_SUSTAIN,
    SYNTH_PARAM_MGX_FILTER_RELEASE,
    SYNTH_PARAM_MGX_LFO_DESTINATION,
    SYNTH_PARAM_MGX_LFO_RATE,
    SYNTH_PARAM_MGX_LFO_DEPTH,
    SYNTH_PARAM_FM_ALGORITHM,
    SYNTH_PARAM_FM_FEEDBACK,
    SYNTH_PARAM_FM_INDEX,
    SYNTH_PARAM_FM_OP1_RATIO,
    SYNTH_PARAM_FM_OP1_LEVEL,
    SYNTH_PARAM_FM_OP1_ATTACK,
    SYNTH_PARAM_FM_OP1_DECAY,
    SYNTH_PARAM_FM_OP1_SUSTAIN,
    SYNTH_PARAM_FM_OP1_RELEASE,
    SYNTH_PARAM_FM_OP2_RATIO,
    SYNTH_PARAM_FM_OP2_LEVEL,
    SYNTH_PARAM_FM_OP2_ATTACK,
    SYNTH_PARAM_FM_OP2_DECAY,
    SYNTH_PARAM_FM_OP2_SUSTAIN,
    SYNTH_PARAM_FM_OP2_RELEASE,
    SYNTH_PARAM_FM_OP3_RATIO,
    SYNTH_PARAM_FM_OP3_LEVEL,
    SYNTH_PARAM_FM_OP3_ATTACK,
    SYNTH_PARAM_FM_OP3_DECAY,
    SYNTH_PARAM_FM_OP3_SUSTAIN,
    SYNTH_PARAM_FM_OP3_RELEASE,
    SYNTH_PARAM_FM_OP4_RATIO,
    SYNTH_PARAM_FM_OP4_LEVEL,
    SYNTH_PARAM_FM_OP4_ATTACK,
    SYNTH_PARAM_FM_OP4_DECAY,
    SYNTH_PARAM_FM_OP4_SUSTAIN,
    SYNTH_PARAM_FM_OP4_RELEASE,
    SYNTH_PARAM_COUNT,
};

// Integer wire/UI units:
// - normalized levels are 0..100
// - times are milliseconds (0..5000)
// - FM ratios and LFO rate are hundredths
// - FM index is hundredths (0..800)
bool synthSetParameter(SynthTrack& track, SynthParameter parameter, int32_t value);
bool synthGetParameter(const SynthTrack& track, SynthParameter parameter, int32_t& value);
bool synthParameterRange(SynthParameter parameter, int32_t& minimum,
                         int32_t& maximum);
bool synthParameterFromName(const char* name, SynthParameter& parameter);
const char* synthParameterName(SynthParameter parameter);
